# GitHub Sponsors configuration
# Documentation: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [nitinya9av]
custom: ["https://bondin.io/niitnydv/support", bondin.io]

